### ISSUE TITLE
Move pdebug import to conditionally compiled file?

### ISSUE THREAD

**Issue by natefinch** [lestrrat/go-jsschema#13]
Would you be open to a PR that moves the imports for go-pdebug into files that only get compiled when you use the -tags debug flag?  i.e. do the same thing in this package as pdebug does itself?

That way when you're not compiling with debug, the code doesn't even import the other package.  This is nice for projects that import jsschema and friends, in that they don't even need to download pdebug unless they're compiling with -debug.

Let me know if you think that's ok, and if so, I'll make a PR.

**Comment by lestrrat** [comment]
I understand the motivation, but wouldn't that mean putting  boilerplate for `pdebug`, and possibly forcing all consumer libraries thereof to do the same?

I just want to have conditional debug with the least amount of code impact (as little, or no method calls if compiled without debug), and I don't want to re-invent this for every project. `pdebug` is not the nicest library in the world, but it does give me this at the cost of forcing one download per user. Can this be achieved?
