### ISSUE TITLE
Go vet errors

### ISSUE THREAD

**Issue by natefinch** [lestrrat/go-jsschema#4]
As seen here: https://goreportcard.com/report/github.com/lestrrat/go-jsschema

(also a couple files appear not to be gofmt'd)

The rest of the issues listed are less critical than those two... but the go vet errors should definitely be fixed.

**Comment by lestrrat** [comment]
It's complaining about the struct containing a lock, to a method that does NOT use the lock. It's a fair warning, but I don't see it as critical.
The fix is easy enough and I'm not saying I won't fix it, just checking if we're on the same wavelength.

**Comment by lestrrat** [comment]
Okay, I understand having automatic detection for these warnings, but I'm going to ignore the gofmt ones, because this:

![image](https://cloud.githubusercontent.com/assets/49281/17451878/15945108-5ba5-11e6-92cb-16e1075bb386.png)

When the time comes for a few lines of change and/or other fix-worthy stuff, I will certainly remove those newlines.

**Comment by natefinch** [comment]
Definitely gofmt is not a big deal.  As you said, it'll get cleaned up the next time you touch the file anyway.

Yes, the go vet errors around passing the value by reference to things that don't use the lock is sort of a false positive.  But it's also easy for those things to later accidentally start using the lock, if a method is added that they call that uses the lock, etc.  Worth fixing, IMO, to prevent problems down the road.  Also, I always obey go vet :)  It's trivial to make the mutex a pointer and then initialize it in New(), and then you never need to worry about it again.

**Comment by lestrrat** [comment]
No, I have a thing with pointers in my structs, as they force  GC scan. I'd rather declare them `func(f *FooThing) DoStuff()` and silence them warnings, if I must.
