### ISSUE TITLE
rename repo and/or package?

### ISSUE THREAD

**Issue by natefinch** [lestrrat/go-jsschema#5]
It's customary to have the last part of the import path be the same as the package name, so that when you do `import "github.com/foo/bar"` then you know the package name is "bar".  Unfortunately, this package doesn't exactly follow that convention.  It's very difficult to know from the last part of the import path "go-jsschema" that the package name would be schema.

Is this something you'd be open to changing?  I know it's a breaking change, but perhaps better now than later?

**Comment by lestrrat** [comment]
So in theory I have no qualms, but on a more meta level, I happen to clone/create lots of repositories with very similar names for, say, python, perl, go, etc, and I just have to wonder how people deal with it...

On the other hand, I have approximately 100 repos that have a `go-` prefix, some mine, some others. I'm not sure if they are such a big issue?

![image](https://cloud.githubusercontent.com/assets/49281/17451767/5959d38c-5ba4-11e6-860f-5f392c851cbf.png)

**Comment by natefinch** [comment]
Early on in go's lifetime, it was common to make things go-foo, but the community has since decided this is a bad idea.  Honestly, just stripping off "go-" is not as big of a deal as the fact that it's 'schema' and not 'jsschema'.  That was the part that really surprised me.  I'm used to stripping off the go-, even though in an ideal world, that wouldn't happen either.  But I get that we have a limited namespace in our github accounts.

**Comment by lestrrat** [comment]
Oh *that* bit! I remember pondering about it, but honestly don't remember what my exact reasoning was. I suspect after trying out for a little bit, I thought `schema` was easier to write than `jsschema` but didn't find a package name like `go-schema` useful.

**Comment by natefinch** [comment]
It's fine, just wanted to bring it up as a potential thing to think about.

**Comment by natefinch** [comment]
I'm going to close this.  renaming once the repo has been out for a while is not really tenable, and since it's just a style thing - meh.
